### ISSUE TITLE
Descrizione

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/rombo#1]
![es4_31_32](https://cloud.githubusercontent.com/assets/3002194/14571291/b7bf86e2-0348-11e6-8e77-c37d5ab4d20f.jpg)

**Comment by FabioZTessitore** [comment]
ok, ora aggiusta la quantità di asterischi stampati. La seconda riga devono essere 3, poi 5 e così via

**Comment by FabioZTessitore** [comment]
hai copiato da tazza

**Comment by Teodoro777** [comment]
Solo visto il conta_aste, ma l'ho migliorato

**Comment by FabioZTessitore** [comment]
vabbé, prova a far inserire all'utente il numero di righe

**Comment by Teodoro777** [comment]
Ho messo la scelta delle righe, la parte superiore funziona sempre.. quella inferiore solo con 5

**Comment by Teodoro777** [comment]
Non ho capito, il risultato dovrebbe essere del tipo: righe = 2 
     *
    ***
     *

**Comment by FabioZTessitore** [comment]
Quelle sono 3

Il sabato 30 aprile 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Ok con i numeri pari diverso.. voi come fareste 4 righe?

**Comment by Teodoro777** [comment]
No  vabbè la parte di sotto si aggiusta per certe righe ma poi va male per altre

**Comment by FabioZTessitore** [comment]
Rombo - Coluccio 3-0

Il sabato 30 aprile 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Se vabbe, in parte va.. Un aiutino?

**Comment by FabioZTessitore** [comment]
Dovresti fare i seguenti passaggi:

1) stampare un solo asterisco per riga
2) stampare il giusto numero di asterischi per riga
3) stampare il giusto numero di spazi prima degli asterischi

Il domenica 1 maggio 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Rombo - Coluccio 3 - 4
Funziona bene con i dispari, e con i pari scala di una riga.. ma così deve essere perchè sta la fila in centro che è unica.

**Comment by FabioZTessitore** [comment]
va bene così
Rombo - Coluccio 4-4
(perché non accetta 19 come input hahaha)

andiamo avanti

**Comment by Teodoro777** [comment]
Sono curioso di vedere come l'avreste fatto voi.. me lo fate?

Il lunedì 2 maggio 2016, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Devi riaggiungermi come collaboratore

**Comment by Teodoro777** [comment]
Vi ho aggiunto
